name: GitHub Pages CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Hugo Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive 
          fetch-depth: 0
          lfs: true

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: |
            ./themes/labmap/scss/src/style.scss
          destination: |
            ./data/css/style.css

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Generate static pages
        run: hugo --minify
      
      - name: Copy data
        run: cp -r ./data/* ./public/

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: labmap.ime.usp.br
